# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_player_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='summary',
            field=models.TextField(default='N/A', null=True),
        ),
    ]
