# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20180824_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(default='undrafted', max_length=255, null=True),
        ),
    ]
