# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='play',
            field=models.CharField(default='benched', max_length=255, null=True),
        ),
    ]
